NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAIMV36WSTXZTW22DAGKMO34N4CWTOC4CZCKEAUIEHT47DQ2VS5FHJLY"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="AstroStellar"
ORG_URL="https://www.astrostellar.org"
ORG_DESCRIPTION="Comets are basically dusty snowballs which orbit the Sun. They are made of ices, such as water, carbon dioxide, ammonia and methane, mixed with dust. These materials came from the time when the Solar System was formed. Comets have an icy center surrounded by a large cloud of gas and dust"
ORG_TWITTER="@AstroStellar3"
ORG_LOGO="https://i.ibb.co/BrYjMsQ/logo-astrostellar.png"
ORG_OFFICIAL_EMAIL="astrostellar00@gmail.com"


[[CURRENCIES]]
code="xcb"
issuer="GAIMV36WSTXZTW22DAGKMO34N4CWTOC4CZCKEAUIEHT47DQ2VS5FHJLY"
anchor_asset="false"
name="Cobalt"
desc="Cobalt is an essential mineral used for batteries in electric cars, computers, and cell phones. Demand for cobalt is increasing as more electric cars are sold, particularly in Europe, where governments are encouraging the sales with generous environmental bonuses."
image="https://i.ibb.co/LvRv9fM/cobalt.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#Cobalt was issued using the open and inclusive Stellar blockchain network.



