NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDVLVAI72GSLWWKTO3TCCFRN2465EU6ZOXTTTTYUNY5GIQ4PP45NGTPH"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="AstroStellar"
ORG_URL="https://www.astrostellar.org"
ORG_DESCRIPTION="Comets are basically dusty snowballs which orbit the Sun. They are made of ices, such as water, carbon dioxide, ammonia and methane, mixed with dust. These materials came from the time when the Solar System was formed. Comets have an icy center surrounded by a large cloud of gas and dust"
ORG_TWITTER="@AstroStellar3"
ORG_LOGO="https://i.ibb.co/BrYjMsQ/logo-astrostellar.png"
ORG_OFFICIAL_EMAIL="astrostellar00@gmail.com"


[[CURRENCIES]]
code="encke"
issuer="GDVLVAI72GSLWWKTO3TCCFRN2465EU6ZOXTTTTYUNY5GIQ4PP45NGTPH"
anchor_asset="false"
name="Encke Comet"
desc="Comet Encke is a small comet. Its nucleus measures approximately 2.98 miles in diameter, which is about a third of the size of the object hypothesized to have led to the demise of the dinosaurs. It takes 3.30 years for Enke to orbit the sun once."
image="https://i.ibb.co/Yhc7YTJ/encke-logo.png"
fixed_number=25000000
max_number=25000000
is_unlimited=false
#Encke Comet was issued using the open and inclusive Stellar blockchain network.



